In [238]:
import pandas as pd

In [239]:
cars = pd.read_csv('../datasets/ml_raw_dataset.csv')

In [240]:
cars.info()

<class 'pandas.DataFrame'>
RangeIndex: 1294757 entries, 0 to 1294756
Data columns (total 18 columns):
 #   Column                Non-Null Count    Dtype
---  ------                --------------    -----
 0   brand                 1294757 non-null  str
 1   name                  1294757 non-null  str
 2   bodyType              1294757 non-null  str
 3   color                 1257029 non-null  str
 4   fuelType              1289815 non-null  str
 5   year                  724644 non-null   float64
 6   mileage               771799 non-null   float64
 7   transmission          1289563 non-null  str
 8   power                 1273353 non-null  float64
 9   price                 1294757 non-null  int64
 10  vehicleConfiguration  724647 non-null   str
 11  engineName            720976 non-null   str
 12  engineDisplacement    717625 non-null   str
 13  date                  1294757 non-null  str
 14  location              1294757 non-null  str
 15  link                  1294757 non-null  str
 16  description           1254405 non-null  str
 17  parse_date            1294757 non-null  str
dtypes: float64(3), int64(1), str(14)
memory usage: 177.8 MB

In [241]:
cars.describe()

                year         mileage         power         price
count  724644.000000   771799.000000  1.273353e+06  1.294757e+06
mean     2009.684535   154893.397115  1.415560e+02  1.444358e+06
std         9.367108   100738.336936  6.563943e+01  1.970257e+06
min      1936.000000     1000.000000  1.000000e+00  2.700000e+02
25%      2003.000000    82000.000000  9.800000e+01  4.250000e+05
50%      2011.000000   144000.000000  1.280000e+02  8.700000e+05
75%      2017.000000   211000.000000  1.630000e+02  1.765000e+06
max      2023.000000  1000000.000000  1.000000e+03  1.500000e+08

Удаляем ненужные столбцы (дата размещения, ссылка на объявление, описание (сложно будет представить его для модели), дата спарсивания объявления)

In [242]:
cars = cars.drop(columns=['date', 'link', 'description', 'parse_date', 'vehicleConfiguration', 'engineName'])

Проверка года выпуска автомобиля

In [243]:
cars = cars.sort_values(by='year')
cars.head(10)

,brand,name,bodyType,color,fuelType,year,mileage,transmission,power,price,engineDisplacement,location
45481,BMW,326,Седан,Синий,Бензин,1936.0,1000.0,Механика,50.0,4500000,2.0 LTR,Ялта
1019699,BMW,326,Седан,Черный,Бензин,1936.0,1000.0,Механика,50.0,650000,2.0 LTR,Тюмень
493223,ГАЗ,М1,Седан,Черный,Бензин,1936.0,NaN,Механика,50.0,2000000,3.3 LTR,Улан-Удэ
524025,BMW,321,Купе,Зеленый,Бензин,1939.0,299000.0,Механика,45.0,400000,2.0 LTR,Воронеж
1202274,Mercedes-Benz,W136,Купе,Красный,Бензин,1939.0,1000.0,Механика,38.0,1550000,1.7 LTR,Санкт-Петербург
31932,BMW,321,Купе,Зеленый,Бензин,1939.0,NaN,Механика,45.0,700000,2.0 LTR,Чита
177782,BMW,321,Открытый,Синий,Бензин,1939.0,10000.0,Механика,45.0,950000,2.0 LTR,Барнаул
1171377,BMW,321,Купе,NaN,Бензин,1939.0,NaN,Механика,45.0,100000,2.0 LTR,Москва
50569,BMW,321,Купе,Желтый,Бензин,1939.0,NaN,Механика,45.0,3500000,2.0 LTR,Вилино
1069874,BMW,321,Купе,Бордовый,Бензин,1939.0,NaN,Механика,45.0,350000,2.0 LTR,Челябинск

Оставляем объявления с автомобилями младше 1980 года

In [244]:
cars = cars[cars['year'] > 1980]
cars.info()

<class 'pandas.DataFrame'>
Index: 718990 entries, 976619 to 1175767
Data columns (total 12 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   brand               718990 non-null  str
 1   name                718990 non-null  str
 2   bodyType            718990 non-null  str
 3   color               701270 non-null  str
 4   fuelType            718936 non-null  str
 5   year                718990 non-null  float64
 6   mileage             418016 non-null  float64
 7   transmission        718990 non-null  str
 8   power               714484 non-null  float64
 9   price               718990 non-null  int64
 10  engineDisplacement  711972 non-null  str
 11  location            718990 non-null  str
dtypes: float64(3), int64(1), str(8)
memory usage: 71.3 MB

Посмотрим редкость брендов на площадке

In [245]:
cars_count = cars.groupby('brand')['year'].count().sort_values(ascending=False).reset_index(name='value')
cars_count

       brand   value
0     Toyota  174494
1       Лада   81523
2      Honda   54929
3     Nissan   53646
4    Hyundai   27842
..       ...     ...
123    Hozon       1
124    Maxus       1
125    Lucid       1
126      SWM       1
127     ЛуАЗ       1

[128 rows x 2 columns]

Оставим только те бренды которые представлены минимум в 300 экземплярах

In [246]:
cars_count = cars_count[cars_count['value'] >= 300]
cars = cars[cars['brand'].isin(cars_count['brand'])]
cars.info()

<class 'pandas.DataFrame'>
Index: 715260 entries, 976619 to 1175767
Data columns (total 12 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   brand               715260 non-null  str
 1   name                715260 non-null  str
 2   bodyType            715260 non-null  str
 3   color               697627 non-null  str
 4   fuelType            715206 non-null  str
 5   year                715260 non-null  float64
 6   mileage             416235 non-null  float64
 7   transmission        715260 non-null  str
 8   power               711308 non-null  float64
 9   price               715260 non-null  int64
 10  engineDisplacement  709090 non-null  str
 11  location            715260 non-null  str
dtypes: float64(3), int64(1), str(8)
memory usage: 70.9 MB

Сконвертируем колонку engineDisplacement в float64

In [247]:
cars = cars.dropna(subset=['engineDisplacement'])
cars['engineDisplacement'].unique()

<StringArray>
['2.0 LTR', '2.8 LTR', '1.5 LTR', '1.8 LTR', '2.7 LTR', '1.6 LTR', '2.4 LTR',
 '2.5 LTR', '5.0 LTR', '1.3 LTR', '2.1 LTR', '1.9 LTR', '4.0 LTR', '2.6 LTR',
 '1.0 LTR', '1.1 LTR', '2.3 LTR', '3.2 LTR', '1.2 LTR', '2.2 LTR', '1.4 LTR',
 '3.4 LTR', '3.0 LTR', '4.2 LTR', '4.1 LTR', '5.5 LTR', '1.7 LTR', '2.9 LTR',
 '0.5 LTR', '4.5 LTR', '3.6 LTR', '5.8 LTR', '3.3 LTR', '0.9 LTR', '4.9 LTR',
 '0.6 LTR', '3.5 LTR', '0.7 LTR', '6.0 LTR', '3.1 LTR', '0.8 LTR', '5.7 LTR',
 '5.2 LTR', '3.8 LTR', '4.6 LTR', '8.0 LTR', '4.3 LTR', '3.9 LTR', '5.4 LTR',
 '3.7 LTR', '4.4 LTR', '6.5 LTR', '5.9 LTR', '4.7 LTR', '6.8 LTR', '8.1 LTR',
 '5.3 LTR', '4.8 LTR', '5.6 LTR', '8.3 LTR', '6.1 LTR', '7.0 LTR', '6.2 LTR',
 '8.4 LTR', '6.4 LTR', '6.7 LTR', '6.3 LTR', '6.6 LTR']
Length: 68, dtype: str

In [248]:
cars['engineDisplacement'] = cars['engineDisplacement'].str.replace(r'\s*LTR', '', regex=True).astype(float)
cars

,brand,name,bodyType,color,fuelType,year,mileage,transmission,power,price,engineDisplacement,location
976619,BMW,5-Series,Седан,Черный,Бензин,1981.0,7000.0,Механика,125.0,260000,2.0,Томск
550317,BMW,5-Series,Седан,Серый,Бензин,1981.0,1000.0,Механика,184.0,30000,2.8,Иркутск
588309,Toyota,Carina,Седан,Белый,Бензин,1981.0,NaN,АКПП,83.0,349000,1.5,Иркутск
430007,Toyota,Celica,Купе,Черный,Бензин,1981.0,NaN,Механика,135.0,700000,2.0,Хабаровск
918879,BMW,5-Series,Седан,NaN,Бензин,1981.0,NaN,Механика,105.0,165000,1.8,Саратов
...,...,...,...,...,...,...,...,...,...,...,...,...
1175770,Kaiyi,E5,Седан,Красный,Бензин,2023.0,NaN,Вариатор,147.0,1899000,1.5,Москва
1076116,Лада,Гранта,Седан,Белый,Бензин,2023.0,NaN,Механика,106.0,848500,1.6,Ярославль
1175769,Kaiyi,E5,Седан,Красный,Бензин,2023.0,NaN,Вариатор,147.0,1899000,1.5,Москва
1175768,Kaiyi,E5,Седан,Белый,Бензин,2023.0,NaN,Вариатор,147.0,1899000,1.5,Москва
1175767,Kaiyi,E5,Седан,Серый,Бензин,2023.0,NaN,Вариатор,147.0,1899000,1.5,Москва

Избавимся от строк которые имеют Nan в значимых столбцах

In [249]:
cars.info()

<class 'pandas.DataFrame'>
Index: 709090 entries, 976619 to 1175767
Data columns (total 12 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   brand               709090 non-null  str
 1   name                709090 non-null  str
 2   bodyType            709090 non-null  str
 3   color               691593 non-null  str
 4   fuelType            709036 non-null  str
 5   year                709090 non-null  float64
 6   mileage             413324 non-null  float64
 7   transmission        709090 non-null  str
 8   power               709082 non-null  float64
 9   price               709090 non-null  int64
 10  engineDisplacement  709090 non-null  float64
 11  location            709090 non-null  str
dtypes: float64(4), int64(1), str(7)
memory usage: 70.3 MB

In [250]:
cars = cars.dropna(subset=['power', 'fuelType'])
cars.info()

<class 'pandas.DataFrame'>
Index: 709028 entries, 976619 to 1175767
Data columns (total 12 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   brand               709028 non-null  str
 1   name                709028 non-null  str
 2   bodyType            709028 non-null  str
 3   color               691538 non-null  str
 4   fuelType            709028 non-null  str
 5   year                709028 non-null  float64
 6   mileage             413290 non-null  float64
 7   transmission        709028 non-null  str
 8   power               709028 non-null  float64
 9   price               709028 non-null  int64
 10  engineDisplacement  709028 non-null  float64
 11  location            709028 non-null  str
dtypes: float64(4), int64(1), str(7)
memory usage: 70.3 MB

Сконвертируем year в int

In [251]:
cars['year'] = cars['year'].astype(int)

Создадим копию датасета с 710 000 строк

In [256]:
cars_710k = cars
cars_710k['color'] = cars_710k['color'].fillna(cars_710k['color'].mode()[0])
cars_710k.to_csv('../datasets/ml_710k.csv', index=False)

Удалим все строки с nan пробегом и сохраним в отдельную копию датасета

In [255]:
cars_410k = cars
cars_410k = cars_410k.dropna(subset=['mileage'])
cars_410k.to_csv('../datasets/ml_410k.csv', index=False)

In [254]:
cars['name'].unique()

<StringArray>
[   '5-Series',      'Carina',      'Celica',     'S-Class',    '3-Series',
  '3102 Волга',      'Patrol',      'Soarer',        '2107',         '412',
 ...
          'E5', 'Bestune B70',      'Alsvin', 'Bestune T55', 'Besturn B70',
  'Wildlander',   'CS95 Plus',   'Eado Plus', 'Bestune T99',       'TX350']
Length: 1494, dtype: str